feat: correct ./ imports
knoxville-utilities-board/ember-unpodify pull request #7
Opened 2023-07-26 16:20 UTC by tsmalls93

2023-07-29 01:49 UTC, TSenter requested changes
I can't comment on the line, but the README still mentions installing via `npm`

2023-07-29 01:49 UTC, TSenter commented on unpodify.js
> +  data = unpodifyComponentTemplateImports(data, appName);
There's also normal templates for routes, not just components.

2023-07-29 01:49 UTC, TSenter commented on unpodify.js
> +  for (type of types) {
```suggestion
  for (const type of types) {
```

2023-07-29 01:49 UTC, TSenter commented on unpodify.js
> +  for (type of types) {
```suggestion
  for (const type of types) {
```

2023-07-29 16:07 UTC, tsmalls93 commented on unpodify.js
> +  data = unpodifyComponentTemplateImports(data, appName);
I didn't think we imported route templates. Do we do that somewhere?

2023-07-29 19:10 UTC, TSenter commented on unpodify.js
> +  data = unpodifyComponentTemplateImports(data, appName);
Ah, imports, right - no, we don't import them anywhere, I was just thinking of the file structure of the application.

2023-08-04 14:12 UTC, TSenter approved these changes

2023-08-04 14:12 UTC, merged